sudo: true
language: php
php:
  - 7.0
  - hhvm

before_install:
  - brew update
  - brew install phantomjs
  - export PHANTOMJS_BINARY_PATH=$(which phantomjs)

script:
  - composer install
  - vendor/bin/phpunit