sudo: true
language: php
php:
  - 7.0
  - hhvm

os:
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install phantomjs; fi
  - export PHANTOMJS_BINARY_PATH=$(which phantomjs)

script:
  - composer install
  - vendor/bin/phpunit