os:
  - osx
  - linux
  - windows

language: php

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - 7.1

before_install:
  - sh .travis/install.sh

install:
  - travis_retry composer self-update
  - travis_retry composer install

before_script:
  - export PHANTOMJS_BINARY_PATH=$(which phantomjs)

script:
  - vendor/bin/phpunit